name: CI

on:
  pull_request:
    branches:
      - 1.x
  push:
    branches:
      - 1.x
    tags-ignore:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

      - name: Security audit
        run: composer audit

      - name: Check code style
        run: vendor/bin/phpcs

      - name: Unit tests
        run: vendor/bin/phpunit